### ISSUE TITLE
All links at "What makes Fisherman stand out?" broken

### ISSUE THREAD

**Issue by jethrokuan** [fisherman/fisherman.github.io#10]

**Comment by bucaran** [comment]
Will fix this after we fix #8 and #9 or before if nothing is done in the next few hours :smile:

**Comment by jethrokuan** [comment]
#8 and #9 is fixed in the fixes branch

**Comment by bucaran** [comment]
OK, I'll fix the links right away.

**Comment by jethrokuan** [comment]
Closed in https://github.com/fisherman/fisherman.github.io/commit/92868e95a57e60db0844ea27e9b0dedc0bab6277
