### ISSUE TITLE
Reduce spacing on small width platforms

### ISSUE THREAD

**Issue by pickfire** [fisherman/fisherman.github.io#4]
https://github.com/fisherman/fisherman.github.io/blob/master/css/style.css#L196

If I am correct, that's the one that makes the spacing between features far apart. I stumbled across this when I am looking if it support mobile platforms.

**Comment by bucaran** [comment]
Do you have any front-end skills? Maybe you can send me a PR :smile:

**Comment by pickfire** [comment]
@bucaran I am still a student, just completed high school. I have a lot of random **unsharpened** skills, you can look at it in my site, ranges from welding to illustration (autocad) to coding (not sure what is front-end/back-end but heard of it) to body language to hand reflexology to piano.

I can send you a PR, just need to test if I am correct, just assign this to me.

**Comment by bucaran** [comment]
@pickfire That's very funny!

Sure, if you want to send a PR we'll review it together and I'll help you out man. :smile:

**Comment by pickfire** [comment]
I think you should remove `margin-bottom: 60px;` from `style.css:173`. I think it should look better in mobile devices, can't test it, I don't have money to buy a smartphone yet.

It looks better on computers too, tested with surf browser locally, it also removes extra spacing after the features section so users can scroll to the **black** section faster (like 2 page).

Well, I am still a newbie at web development, I hope you could point out my mistakes. In progress in making my site viewable in mobile devices.

I like that black background color in the **black** section that I just mentioned, it just stands out, I seldom see nice white on black backgrounds.

**Comment by bucaran** [comment]
Just change it, send a PR, I'll test locally and then we'll merge.

**Comment by jethrokuan** [comment]
fixed by a2e9495614032eade54199f13e6ba42a339e6b2a

**Comment by bucaran** [comment]
:+1:
