### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by radek-sprta** [fisherman/fisherman.github.io#4]
Hi,
I've noticed, that Fisherman seem to index only plugins on Github. Do you plan to add a support to Gitlab (if technically possible)?

Cheers.

**Comment by jbucaran** [comment]
@radek-sprta Do you mean on the website or the plugin manager? I think you mean on the website. If that's the case then I think it is technically possible – everything is possible with JavaScript! 😄:+1:.

I'd be happy to review and merge a PR if you would like to add this feature.

Cheers!
