### ISSUE TITLE
Search function for plugins

### ISSUE THREAD

**Issue by jethrokuan** [fisherman/fisherman.github.io#6]
- [ ] clicking div should show result
- [ ] width of search bar should be logo width at max
- [ ] Search bar should be big and pretty
- [ ] Should look good on mobile devices

**Comment by bucaran** [comment]
![results](https://cloud.githubusercontent.com/assets/8317250/13208142/5b5a8d98-d959-11e5-982f-ce5b9f7c254d.png)
![default](https://cloud.githubusercontent.com/assets/8317250/13208143/5b5b4094-d959-11e5-8b14-e0a8e2717777.png)

**Comment by bucaran** [comment]
+ [ ] labels should not be perfect circles, and wider

**Comment by pickfire** [comment]
@bucaran, probably it would better if the features section can be at the bottom. For more info, I use [surf browser](surf.suckless.org)

![2016-02-23-193003_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/13250766/b38e10da-da66-11e5-89c2-52958b8d9e98.png)

- [ ] features section at the bottom of page

**Comment by bucaran** [comment]
@pickfire Can you use an image editor and cut, crop and paste to create a simple (nothing fancy) mockup of what you mean? Here is a full screenshot you can use.

![screencapture-fisherman-sh-1456229448737](https://cloud.githubusercontent.com/assets/8317250/13251173/eefa8846-da71-11e5-9523-c5d71d914f7e.png)

**Comment by pickfire** [comment]
@bucaran, I am not actually very sure what you mean. I just mean that the **whole browser** should just look like the photo you showed, it can make fisherman's site more professional.

![s](https://cloud.githubusercontent.com/assets/8317250/13208143/5b5b4094-d959-11e5-8b14-e0a8e2717777.png)

**Comment by bucaran** [comment]
Done

**Comment by pickfire** [comment]
What? So fast?

**Comment by bucaran** [comment]
@pickfire It's just a trivial edit. Let me know if it looks weird.

**Comment by pickfire** [comment]
It still looks weird but better than back then.

Ah, it's only just a trivial edit for you? Probably because you have a lot of experience?

Well, I am still young, have much to learn.

**Comment by bucaran** [comment]
Why are we having a conversation about the same thing across two different issues?
